### ISSUE TITLE
[Feature]: 可以更新beta24嘛

### ISSUE THREAD

**Issue by qdpatriotcn** [2096779623/lx-music-mobile#1]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，但没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，但没有发现类似的问题

### 问题描述

感谢

### 描述你想要的解决方案

beta24

### 描述你考虑过的替代方案

谢谢

### 附加信息

，，，

**Comment by 2096779623** [comment]
已更新

**Comment by qdpatriotcn** [comment]
> 已更新

谢谢💖
